#!/usr/bin/with-contenv sh

. /app/cloudflare.sh
. /config/cloudflare.conf

# 优选cloudflare ip
echo "----------------------------------------------------------------"
echo "必须无代理环境运行此docker镜像，如宿主机需要代理环境，可以macvlan模式运行"
echo "----------------------------------------------------------------"
CloudflareST
echo "开始获取优选ip"
echo "----------------------------------------------------------------"
BestIpAddress=$(getBestIpAddress)
DnsIpAddress=$(getDnsRecordIp $CF_ZONE_ID $CF_RECORD_ID)

if [ "$BestIpAddress" == "" ]; then
  echo "----------------------------------------------------------------"
  echo "ERROR: ip优选脚本运行失败，未获得优选ip"
  echo "----------------------------------------------------------------"
  exit 1
else
  echo "----------------------------------------------------------------"
  echo "获取的优选ip为:$BestIpAddress"
  echo "----------------------------------------------------------------"
fi

if [ "$BestIpAddress" != "$DnsIpAddress" ]; then
  echo "Updating CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $BestIpAddress..."
  update=$(updateDnsRecord $CF_ZONE_ID $CF_RECORD_ID $CF_RECORD_NAME $BestIpAddress)

  if [ "$update" == "null" ]; then
    echo "ERROR: Failed to update CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $BestIpAddress"
  else
    echo "CloudFlare DNS record $CF_RECORD_NAME ($BestIpAddress) updated successfully."
  fi

else
  echo "No DNS update required for $CF_RECORD_NAME ($DnsIpAddress)."
fi
