#!/usr/bin/with-contenv sh

. /app/cloudflare.sh
. /config/cloudflare.conf

DnsIpAddress=$(getDnsRecordIp $CF_ZONE_ID $CF_RECORD_ID)
CloudflareST
BestIpAddress=$(getBestIpAddress)

if [ "$BestIpAddress" == "" ]; then
  echo "----------------------------------------------------------------"
  echo "ERROR: ip优选脚本运行失败"
  echo "----------------------------------------------------------------"
  exit 1
fi

if [ "$BestIpAddress" != "$DnsIpAddress" ]; then
  echo "Updating CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $BestIpAddress..."
  update=$(updateDnsRecord $CF_ZONE_ID $CF_RECORD_ID $CF_RECORD_NAME $BestIpAddress)

  if [ "$update" == "null" ]; then
    echo "ERROR: Failed to update CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $BestIpAddress"
  else
    echo "CloudFlare DNS record $CF_RECORD_NAME ($BestIpAddress) updated successfully."
  fi

else
  echo "No DNS update required for $CF_RECORD_NAME ($DnsIpAddress)."
fi
